package ui.drawer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainMenuUI extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public MainMenuUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        minesweeperButton = new javax.swing.JButton();
        sudokuButton = new javax.swing.JButton();
        favouriteListButton = new javax.swing.JButton();
        screenTittle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(2, 153, 147));
        setForeground(new java.awt.Color(204, 255, 255));

        minesweeperButton.setText("Play Minesweeper");
        minesweeperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sudokuButton.setText("Play Sudoku");
        minesweeperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        favouriteListButton.setText("Look at Favourites List");
        minesweeperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        screenTittle.setFont(new java.awt.Font("Wingdings", 2, 24)); // NOI18N
        screenTittle.setText("Welcome to Wikteria");

//        add(minesweeperButton);
//        add(sudokuButton);
//        add(favouriteListButton);
        add(screenTittle, BorderLayout.CENTER);
//
//        minesweeperButton.setBounds(414,28,423,37);
//        sudokuButton.setBounds();
//        favouriteListButton.setBounds();
        screenTittle.setBounds(414,28,423,37);

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        this.setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(201, 201, 201)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addComponent(sudokuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(favouriteListButton)
//                                                        .addComponent(minesweeperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(79, 79, 79)
//                                                .addComponent(screenTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap(160, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(23, 23, 23)
//                                .addComponent(screenTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
//                                .addComponent(minesweeperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(sudokuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(favouriteListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(29, 29, 29))
//        );
    }

    private void jButton2ActionPerformed(ActionEvent evt) {
        //TODO
    }

    private void jButton3ActionPerformed(ActionEvent evt) {
        //TODO
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton minesweeperButton;
    private javax.swing.JButton sudokuButton;
    private javax.swing.JButton favouriteListButton;
    private javax.swing.JLabel screenTittle;
    // End of variables declaration
}

//public class a {
//    protected static JFrame frame = new JFrame();
//    protected static JPanel panel = new JPanel();
//
//    private static JButton minesweeperButton = new JButton();
//    private static JButton sudokuButton = new JButton();
//    private static JButton favouriteListButton = new JButton();
//
//    private static JLabel screenTitle = new JLabel();
//
//    private static JPanel mainPanel = new JPanel();
//
//    public MainMenuUI() {
//        setupFrame();
//    }
//
//    private void initComponents() {
//
//    }
//
//    private void setupFrame() {
//        frame.setSize(500,320);
//        frame.setLayout(null);
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setVisible(true);
//
//        frame.add(panel);
//        setMinesweeper();
//        setSudoku();
//        setFavouriteList();
//        setTitle();
//    }
//
//    private void setTitle() {
//        frame.add(screenTitle);
//        screenTitle.setBounds(50,50,250,30);
//    }
//
//    private void setFavouriteList() {
//        favouriteListButton.setBounds(50,200,100,40);
//        frame.add(favouriteListButton);
//        favouriteListButton.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                //resetFrame();
//                new FavouriteListUI();
//            }
//        });
//    }
//
//    private void setMinesweeper() {
//        minesweeperButton.setBounds(50,100,100,40);
//        frame.add(minesweeperButton);
//        minesweeperButton.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
////                frame.removeAll();
////                frame.revalidate();
//                //frame.setVisible(false);
//                frame.remove(screenTitle);
//                frame.revalidate();
//                new MinesweeperUI();
//            }
//        });
//    }
//
//    private void setSudoku() {
//        sudokuButton.setBounds(50,150,100,40);
//        frame.add(sudokuButton);
//        sudokuButton.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                //resetFrame();
//                new SudokuUI();
//            }
//        });
//    }
//
//    public void resetFrame() {
//        frame.remove(minesweeperButton);
//        frame.remove(sudokuButton);
//        frame.remove(favouriteListButton);
//        frame.remove(screenTitle);
//    }
//
//    public void test() {
//        minesweeperButton.setVisible(false);
//    }
//}
