package utils;

import org.junit.jupiter.api.Test;
import testingUtils.DistributionArray;

import java.util.ArrayList;

//TODO find a better way to test RNG
public class RandomNumberGeneratorTest {

    //this test is supposed to test the distribution generated by the RNG class
    //to do so, the interval [0.0,1.0] will be divided into 20 subintervals of size 0.05
    //the test will generate 10000 random numbers and the result will be shown in a histogram such that
    //each asterisk will represent 100 times that a number in the interval was generated (will always be rounded down)
    @Test
    public void testDistribution() {
        RandomNumberGenerator rng = new RandomNumberGenerator();
        DistributionArray da = new DistributionArray();

        for (int i = 0; i < 10000; i++) {
            da.addEntry(rng.generateNumber());
        }

        da.printDistribution();
    }

    @Test
    public void testDistributionArray() {
        DistributionArray da = new DistributionArray();
        da.addEntry(0.543232);
    }
}
